### ISSUE TITLE
Path to php executable is not properly escaped when stored in UserConfiguration.json (affects default MAMP bin php exec)

### ISSUE THREAD

**Issue by oliveratgithub** [VineCode/PHPLint.novaextension#3]
Manually setting the php executable path to the php bin included within MAMP seems not to work - could that be?

`/Applications/MAMP/bin/php/php7.4.2/bin/php`
=> in the `UserConfiguration.json` the slashes in the path will be escaped with `\`

When opening PHP files & validating on save, the Debug Log only displays a message as follows:

`PHPLint[21:23:39.013000] Errors parsing /Volumes/macOS/Users/me/Sites/project/index.php`

**Comment by oliveratgithub** [comment]
Oh I got it to work! The path to the php executable is not properly escaped in the `UserConfiguration.json`:

- manually escaped the dots `\.` (in addition to the forward slashes `\/`) and now it's working

`"VineCode.PHPLint.execPath" : "\/Applications\/MAMP\/bin\/php\/php7\.4\.2\/bin\/php"`

So this is a bug in the PHPLint extension :)

**Comment by vinecode-andy** [comment]
@oliveratgithub Thanks for your updates on this. I have pushed a new version, could you let me know if this resolves the issue for you.

**Comment by oliveratgithub** [comment]
> @oliveratgithub Thanks for your updates on this. I have pushed a new version, could you let me know if this resolves the issue for you.

The bug with reading the path to the php exec may be fixed now @vinecode-andy – so this issue here may be closed, I guess.
