### ISSUE TITLE
Extension reports "Could not open input file:"

### ISSUE THREAD

**Issue by legsak1mbo** [VineCode/PHPLint.novaextension#7]
Just installed Nova and the extension. Working against a remote project files open fine with Nova but the extension reports:-

```
Could not open input file: /remote/path/to/file/index.php
```

**Comment by legsak1mbo** [comment]
Just installed Nova and the extension. Working against a remote project files open file with Nova but the extension reports:-

```
Could not open input file: /remote/path/to/file/index.php
```

**Comment by charger3444** [comment]
Same here. Doesn't works on remote files.

**Comment by 314mic** [comment]
Same here.

**Comment by vinecode-andy** [comment]
At the moment I don't plan to add support for remote files. But I will take a look at the Nova API to see how easy this could be added.
