### ISSUE TITLE
installation instructions unclear

### ISSUE THREAD

**Issue by dansroka** [VineCode/PHPLint.novaextension#8]
The installation instructions in the readme are unclear for me on a couple points.

**(1) installing PHP**
They say "you must ensure that php is installed on your system" and recommend using Homebrew to do it. Yet, Mac OS X comes with PHP pre-installed — you just need to enable it (such as from [these instructions](https://coolestguidesontheplanet.com/install-apache-mysql-php-on-macos-catalina-10-15/)).

- If you already have the default installation of PHP running on your system, should PHPLint work?
- Or does the Homebrew installation you recommend install components that are not part of OS X's built-in version on PHP?
- Homebrew also has a [formula for PHPLint](https://formulae.brew.sh/formula/phplint#default) specifically. Should this be installed as well?

**(2) Executable path**
In the instructions, the executable path is just a placeholder ("/path/to/sass"). Yet both the built-in version of PHP and the Homebrew version install PHP to a specific location: /usr/bin/php. The instructions should say that this is a standard default location.

Thank you.

**Comment by vinecode-andy** [comment]
Thanks @dansroka I will try to make the instructions clearer but just for info: 

- If you have PHP installed and it is available on the standard path you don't need to install from Homebrew. 
- Homebrew can just be a standard install, nothing extra is required. The pre-installed PHP on OSX is usually out of date so I have never used it.
- We just use the standard PHP binary. the PHPLint formula is not used. 

Re the executable path, I will update this. I maintain the sass extension too, often working late fuelled by huge amounts of coffee so it looks like I typo'd the wrong path.
