### ISSUE TITLE
Nova has this build in?

### ISSUE THREAD

**Issue by AddictArts** [VineCode/PHPLint.novaextension#9]
The README doesn't make it clear what this extension does beyond what Nova has already. Could you clarify why the need for this extension. Thanks for the help.

**Comment by vinecode-andy** [comment]
Hey @AddictArts Nova has this built in now, but didn't when I started beta testing. Most of my development work is in PHP so I whipped up this extension. I kinda just keep it going in case some cool addition comes to mind that can be added.
